export const FETCH_PROJECTS="FETCH_PROJECTS";
export const FETCH_PROJECT_SUCCESS="FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAIL="FETCH_PROJECT_FAIL";
export const INITIALISE_FOR_UPDATE="INITIALISE_FOR_UPDATE";
export const FETCH_TASKS="FETCH_TASKS";
export const FETCH_TASK_SUCCESS="FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAIL="FETCH_TASK_FAIL";