export const FETCH_PROJECTS="FETCH_PROJECTS";
export const FETCH_PROJECT_SUCCESS="FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAIL="FETCH_PROJECT_FAIL";
export const INITIALISE_FOR_UPDATE="INITIALISE_FOR_UPDATE";
export const UPDATE_PROJECT_VALUE_CHANGED="UPDATE_PROJECT_VALUE_CHANGED";
export const UPDATE_PROJECT="UPDATE_PROJECT";
export const UPDATE_PROJECT_SUCCESS="UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL="UPDATE_PROJECT_FAIL";