export const FETCH_PROJECTS="FETCH_PROJECTS";
export const FETCH_PROJECT_SUCCESS="FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAIL="FETCH_PROJECT_FAIL";
export const INITIALISE_FOR_UPDATE="INITIALISE_FOR_UPDATE";
